---
title: "Moabit Shapefiles"
author: "Cedric Scherer"
date: "27th of October 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

## Setup

```{r prep, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(patchwork)

theme_set(theme_minimal())
```

## Data

```{r data}
## Prognoseräume Berlin -> shape LOR Moabit (but contains also non-Moabit areas in the south...)
## source: https://data.technologiestiftung-berlin.de/dataset/lor_prognoseraeume/en
sf_moabit <- 
  sf::read_sf(dsn = here::here("data", "lor_prognoseraeume", "lor_prognoseraeume.shp"), 
              layer = "lor_prognoseraeume") %>% 
  filter(spatial_al == "Moabit")

## Ortsteile Berlin -> shape quarter Moabit 
## source: https://daten.berlin.de/datensaetze/rbs-ortsteile-dezember-2014
sf_moabit <- 
  sf::read_sf(dsn = here::here("data", "RBS_OD_ORT_1412", "RBS_OD_ORT_1412.shp"), 
              layer = "RBS_OD_ORT_1412") %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs") %>% 
  filter(ORT == "0102")

## Berlin Buildings
## source: https://opendata-esri-de.opendata.arcgis.com/datasets/ecf431fd8c394ee1b2fd7d54563e7b81_0
sf_build <-
  sf::read_sf(dsn = here::here("data", "Gebäude__Berlin", "Gebäude__Berlin.shp"), 
              layer = "Gebäude__Berlin") %>%
  st_intersection(sf_moabit)
  
## additional shapes: landuse, roads, railways, water bodies
## source: https://download.geofabrik.de/europe/germany/berlin.html
sf_landuse <-
  sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_landuse_a_free_1.shp"), 
              layer = "gis_osm_landuse_a_free_1") %>% 
  st_intersection(sf_moabit) %>% 
  mutate(green = if_else(fclass %in% c("park", "recreation_ground", "cemetery", 
                                       "scrub", "forest", "heath", "allotments", 
                                       "grass"), "T", "F")) %>% 
  dplyr::select(osm_id, code, fclass, name, green)

sf_roads <-
  sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_roads_free_1.shp"), 
              layer = "gis_osm_roads_free_1") %>% 
  st_intersection(sf_moabit) %>% 
  filter(!fclass %in% c("steps", "bridleway", "pedestrian", "cycleway")) %>% 
  mutate(
    oneway = if_else(oneway == "B", "T", "F"),
    stroke = if_else(fclass %in% c("path", "footway"), 0.1, 0.2),
    stroke = factor(stroke, levels = c("0.1", "0.2"))
  ) %>% 
  dplyr::select(osm_id, code, fclass, name, ref, maxspeed, oneway, bridge, tunnel, stroke, layer)
  
sf_rails <-
  sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_railways_free_1.shp"), 
              layer = "gis_osm_railways_free_1") %>% 
  st_intersection(sf_moabit) %>% 
  dplyr::select(osm_id, code, fclass, name)

sf_water <- 
  sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_water_a_free_1.shp"), 
              layer = "gis_osm_water_a_free_1") %>% 
  st_intersection(sf_moabit) %>% 
  dplyr::select(osm_id, code, fclass, name)
```

## Write Shapefiles

```{r write-shapefiles}
st_write(sf_moabit, dsn = here::here("shp", "moabit_district.shp"), 
         layer = "moabit_district.shp", driver = "ESRI Shapefile")

st_write(sf_build, dsn = here::here("shp", "moabit_build.shp"), 
         layer = "moabit_build.shp", driver = "ESRI Shapefile")

st_write(sf_landuse, dsn = here::here("shp", "moabit_landuse.shp"), 
         layer = "moabit_landuse.shp", driver = "ESRI Shapefile")

st_write(sf_roads, dsn = here::here("shp", "moabit_roads.shp"), 
         layer = "moabit_roads.shp", driver = "ESRI Shapefile")

st_write(sf_rails, dsn = here::here("shp", "moabit_rails.shp"), 
         layer = "moabit_rails.shp", driver = "ESRI Shapefile")

st_write(sf_water, dsn = here::here("shp", "moabit_water.shp"), 
         layer = "moabit_water.shp", driver = "ESRI Shapefile")
```

## Overview shapes

```{r facet-shapes, fig.width = 12, fig.height = 10.7}
theme_update(
  plot.title = element_text(face = "bold", hjust = 0.5, margin = margin(t = 12, b = 3)),
  axis.text = element_text(size = 8, color = "grey50"),
  panel.grid.major = element_line(size = 0.3, color = "grey90")
)

d <- ggplot(sf_moabit) + geom_sf() + ggtitle("moabit_district.shp")
b <- ggplot(sf_build) + geom_sf(aes(fill = AnzahlDerO), color = NA) + ggtitle("moabit_build.shp")
l <- ggplot(sf_landuse) + geom_sf(aes(fill = green)) + ggtitle("moabit_landuse.shp")
s <- ggplot(sf_roads) + geom_sf(aes(color = stroke)) + ggtitle("moabit_roads.shp")
r <- ggplot(sf_rails) + geom_sf(aes(color = fclass)) + ggtitle("moabit_rails.shp")
w <- ggplot(sf_water) + geom_sf() + ggtitle("moabit_water.shp")

facet <- (d + b + l + s + r + w) * 
  scale_x_continuous(limits = c(13.312, 13.3738)) * 
  scale_y_continuous(limits = c(52.517, 52.542)) + 
  plot_layout(nrow = 3)

ggsave(here::here("img", "shapes_overview.pdf"), plot = facet,
       width = 12, height = 10.7, device = cairo_pdf)
```

## Example Map

```{r map, fig.width = 12, fig.height = 10.88}
(moabit <- 
  sf_build %>% 
  mutate(levels = if_else(AnzahlDerO > 7, "7", as.character(AnzahlDerO))) %>% 
  ggplot() +
    geom_sf(data = sf_water,
             color = "#284756",
             fill = "#284756") +
    geom_sf(data = sf_landuse %>% 
            filter(green == "T"),
            color = NA,
            fill = "#183222") +
    geom_sf(data = sf_rails,
            color = "grey15",
            size = 0.25) +
    geom_sf(data = sf_roads,
            aes(size = stroke),
            color = "grey25") +
    geom_sf(aes(fill = levels), 
            color = "black",
            lwd = 0.005, 
            show.legend = "point") + 
    scale_fill_viridis_d(name = "Above Ground Building Levels", 
                         option = "plasma",
                         labels = c(as.character(1:6), "\u22657")) +
    scale_size_manual(values = c(0.125, 0.3), guide = F) +
    scale_x_continuous(expand = c(0.001, 0.001)) +
    scale_y_continuous(expand = c(0.001, 0.001)) +
    guides(fill = guide_legend(title.position = "top", 
                               title.hjust = 0.5, nrow = 1,
                               label.position = "right",
                               override.aes = list(size = 8, shape = 21))) +
    labs(title = "Moabit – Berlin 21",
         caption = "Visualization by Cédric Scherer  •  Data by Geoportal Berlin & OpenStreetMap") +
    theme(plot.background = element_rect(color = "grey40", 
                                         fill = "black",
                                         size = 20),
          plot.margin = margin(25, 35, 25, 35),
          axis.text = element_blank(),
          panel.grid.major = element_blank(),
          plot.title = element_text(color = "grey60",
                                    size = 42,
                                    face = "bold",
                                    hjust = 0.5,
                                    margin = margin(t = 18, b = 18)),
          plot.caption = element_text(color = "grey30",
                                      size = 12,
                                      face = "bold",
                                      hjust = 0.5,
                                      margin = margin(t = 18, b = 12)),
          legend.position = "bottom",
          legend.title = element_text(color = "grey45",
                                      size = 15,
                                      face = "bold"),
          legend.text = element_text(color = "grey45",
                                     size = 12),
          legend.box.margin = margin(0.5, 0, 0, 0, "cm"), 
          legend.box.spacing = unit(0.2, "cm"), 
          legend.key.size = unit(1.4, "lines")))

ggsave(here::here("img", "build_levels.pdf"), plot = moabit,
       width = 12, height = 10.88, device = cairo_pdf)
```

***

## Session Info

```{r session-info}
sessionInfo()
```

