---
title: "Kreuzberg Shapefiles"
author: "Cedric Scherer"
date: "27th of October 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

## Setup

```{r prep, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(patchwork)

theme_set(theme_minimal())
```

## Data

```{r data}
## Prognoseräume Berlin -> shape LOR Kreuzberg
## source: https://data.technologiestiftung-berlin.de/dataset/lor_prognoseraeume/en
sf_xberg <- 
  sf::read_sf(dsn = here::here("data", "lor_prognoseraeume", "lor_prognoseraeume.shp"), 
              layer = "lor_prognoseraeume") %>% 
  filter(str_detect(spatial_al, "Kreuzberg"))

## Berlin Buildings
## source: https://opendata-esri-de.opendata.arcgis.com/datasets/ecf431fd8c394ee1b2fd7d54563e7b81_0
sf_build <-
  sf::read_sf(dsn = here::here("data", "Gebäude__Berlin", "Gebäude__Berlin.shp"), 
              layer = "Gebäude__Berlin") %>%
  st_intersection(sf_xberg)
  
## additional shapes: landuse, roads, railways, water bodies
## source: https://download.geofabrik.de/europe/germany/berlin.html
sf_landuse <-
  sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_landuse_a_free_1.shp"), 
              layer = "gis_osm_landuse_a_free_1") %>% 
  st_intersection(sf_xberg) %>% 
  mutate(green = if_else(fclass %in% c("park", "recreation_ground", "cemetery", 
                                       "scrub", "forest", "heath", "allotments", 
                                       "grass"), "T", "F")) %>% 
  dplyr::select(osm_id, code, fclass, name, green)

sf_roads <-
  sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_roads_free_1.shp"), 
              layer = "gis_osm_roads_free_1") %>% 
  st_intersection(sf_xberg) %>% 
  filter(!fclass %in% c("steps", "bridleway", "pedestrian", "cycleway")) %>% 
  mutate(
    oneway = if_else(oneway == "B", "T", "F"),
    stroke = if_else(fclass %in% c("path", "footway"), 0.1, 0.2),
    stroke = factor(stroke, levels = c("0.1", "0.2"))
  ) %>% 
  dplyr::select(osm_id, code, fclass, name, ref, maxspeed, oneway, bridge, tunnel, stroke, layer)
  
sf_rails <-
  sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_railways_free_1.shp"), 
              layer = "gis_osm_railways_free_1") %>% 
  st_intersection(sf_xberg) %>% 
  dplyr::select(osm_id, code, fclass, name)

sf_water <- 
  sf::read_sf(dsn = here::here("data", "berlin-latest-free.shp", "gis_osm_water_a_free_1.shp"), 
              layer = "gis_osm_water_a_free_1") %>% 
  st_intersection(sf_xberg) %>% 
  dplyr::select(osm_id, code, fclass, name)
```

## Example Map

```{r map, fig.width = 15, fig.height = 9.914}
(xberg <- 
  sf_build %>% 
  filter(!is.na(AnzahlDerO)) %>% 
  mutate(levels = if_else(AnzahlDerO > 7, "7", as.character(AnzahlDerO))) %>% 
  ggplot() +
    geom_sf(data = sf_water,
             color = "#9db3d1",
             fill = "#9db3d1") +
    geom_sf(data = sf_landuse %>% 
            filter(green == "T"),
            color = NA,
            fill = "#072f0c") +
    geom_sf(data = sf_rails,
            color = "grey15",
            size = 0.25) +
    geom_sf(data = sf_roads,
            aes(size = stroke),
            color = "grey25") +
    geom_sf(aes(fill = levels), 
            color = "black",
            lwd = 0.005, 
            show.legend = "point") + 
    scico::scale_fill_scico_d(palette = "batlow", 
                              name = "Above Ground Building Levels", 
                              labels = c(as.character(1:6), "\u22657")) +
    scale_size_manual(values = c(0.125, 0.3), guide = F) +
    scale_x_continuous(expand = c(0.001, 0.001)) +
    scale_y_continuous(expand = c(0.001, 0.001)) +
    guides(fill = guide_legend(title.position = "top", 
                               title.hjust = 0.5, nrow = 1,
                               label.position = "right",
                               override.aes = list(size = 8, shape = 21))) +
    labs(title = "Kreuzberg – Berlin 361",
         caption = "Visualization by Cédric Scherer  •  Data by Geoportal Berlin & OpenStreetMap contributors") +
    theme(plot.background = element_rect(color = "#bf9aa7", 
                                         fill = "black",
                                         size = 10),
          plot.margin = margin(25, 35, 25, 35),
          axis.text = element_blank(),
          panel.grid.major = element_blank(),
          plot.title = element_text(family = "Modern No. 20",
                                    color = "#ffdae6",
                                    size = 48,
                                    face = "bold",
                                    hjust = 0.5,
                                    margin = margin(t = 18, b = 18)),
          plot.caption = element_text(family = "Modern No. 20",
                                      color = "#ffc0cb",
                                      size = 14,
                                      face = "bold",
                                      hjust = 0.5,
                                      margin = margin(t = 18, b = 12)),
          legend.position = c(0.8, 0.1),
          legend.title = element_text(family = "Modern No. 20",
                                      color = "#ffdae6",
                                      size = 18,
                                      face = "bold"),
          legend.text = element_text(family = "Modern No. 20",
                                     color = "#bf9aa7",
                                     face = "bold",
                                     size = 14),
          legend.box.margin = margin(0.5, 0, 0, 0, "cm"), 
          legend.box.spacing = unit(0.2, "cm"), 
          legend.key.size = unit(1.4, "lines")))

ggsave(here::here("img", "build_levels_xberg_light.pdf"), plot = xberg,
       width = 15, height = 9.914, device = cairo_pdf)
```

***

## Session Info

```{r session-info}
sessionInfo()
```
